### PR TITLE
Start adding minutes for srcmgr@ meetings

### PR DESCRIPTION
**Pull request by markjdb**

### CODE REVIEW

**Review by bsdjhb — APPROVED** [review]
Maybe 'TBA' instead of 'XXX' for the Charter link?

**Comment by markjdb** [comment]
> Maybe 'TBA' instead of 'XXX' for the Charter link?

Yep, fixed.

**Review by bsdimp — APPROVED** [review]

**Comment by bsdimp** [comment]
Looks good to me.

**Review by emaste — APPROVED** [review]

**Comment by bsdimp** [comment]
3/4 rule: I've merged it. If jhb wants changes we can update.

**Pull request merged**
